spring.application.name=JavaProjectApplication

# Data regarding the link of the api with the database
spring.datasource.url=jdbc:postgresql://localhost:5432/javaproject
spring.datasource.username=postgres
spring.datasource.password=example
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springframework.web=DEBUG


